spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: deepseek-r1
    openai:
      api-key: sk-9u6ZLIknSoJmQUCzGdbTFHclvBjkHrNJP7k78lkM1iEWUWdF
      base-url: https://api.chatanywhere.tech
#      api-key: sk-KvxTWiP6zrYOXa8b8f9e461b4d394506BcD89c8964106939
#      base-url: https://ai.huice.com/one-api
      image:
        options:
          model: gpt-4-dalle
          n: 1
    deepseek:
      api-key: sk-57dacaf225364380925bc76d7af4bb1f
      base-url: https://api.deepseek.com/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chatMemory?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.aialibaba.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

server:
  port: 8080